---
# Add new network interfaces using DHCP
# This is intended to allow you to add an interface to a server without a
# full network restart.

- name: network cloud | get existing config
  find:
    file_type: file
    paths: /etc/sysconfig/network-scripts
    patterns: "ifcfg-*"
    recurse: false
  register: network_cloud_existing

- name: network cloud | add nics
  become: true
  template:
    src: etc-sysconfig-network-scripts-ifcfg.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ item }}
    mode: 0644
  when: >
    (network_cloud_existing.files | selectattr("path", "equalto",
       "/etc/sysconfig/network-scripts/ifcfg-" + item)
       | list | length) == 0
  with_items: >
    {{
      network_cloud_interfaces | default(ansible_interfaces) |
      select('search', network_cloud_interface_regex) | list
    }}
  register: network_cloud_modified

- name: network cloud | disable default routes
  become: true
  copy:
    dest: /etc/dhcp/dhclient-enter-hooks
    src: dhcp-dhclient-enter-hooks
    mode: 0755

- name: network cloud | start new nics
  become: true
  command: /usr/sbin/ifup {{ item.item }}
  when: item is changed
  with_items:
    - "{{ network_cloud_modified.results }}"
